FROM debian:trixie-slim
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
ENV PYTHONUNBUFFERED=1
RUN pip install --break-system-packages websockets psutil numpy pillow
WORKDIR /app
COPY camera_stream.py .
